name: MinecraftPyServer
main: com.macuyiko.minecraftpyserver.MinecraftPyServerPlugin
version: 0.10
commands:
  py:
    description: Execute Python code on Jython interpreter
    usage: /py code
  pyrestart:
    description: Restart Jython interpreter
    usage: /pyrestart
  pyload:
    description: Execute a server-side Python file on Jython interpreter
    usage: /pyload file
permissions:
  chatcommands:
    default: op
    description: Players who can use chat commands
